### ISSUE TITLE
IRQ2 and 3 on Mega2560 on 2nd UART

### ISSUE THREAD

**Issue by jabadabado** [ukw100/IRMP#10]
Hi,
A really great library! 
I just noticed that the 2nd UART on Atmega2560 is using the same pins for INT2 and INT3. Would it be possible to use IRQ pins other than the first two?

**Comment by jabadabado** [comment]
Hi,
A really great library!
I just noticed that the 2nd UART on Atmega2560 is using the same pins for INT0 and INT1. Would it be possible to use IRQ pins other than the first two?

@jabadabado

**Comment by ArminJo** [comment]
Of course, just use INT4 and INT5 😁
