### ISSUE TITLE
Detect if IRMP is currently receiving

### ISSUE THREAD

**Issue by Roxolasu** [ukw100/IRMP#21]
### Arduino Platform
* [x] Arduino ATmega328* board (UNO, Nano)

### IDE
* [x] Arduino IDE

### IR-Protocol
* [x] NEC

### Example to reproduce the issue
* [x] Interrupt

### Version
* [x] Yes I use the [latest release](https://github.com/ukw100/IRMP/releases) and verified this!
* [ ] Other - please specify

### Additional context
I'm trying to use IRMP (using interrupts / callback) in conjunction with code which disables interrupts (NeoPixel). For this, I want to skip the code which disables interrupts if IRMP is currently receiving something.
 
Is there a way to check if IRMP is currently expecting more data? (I tried some flags like irmp_ir_detected, but they didn't seem to have the expected effect)

**Comment by ArminJo** [comment]
Use the new function bool irmp_IsBusy()

**Comment by Roxolasu** [comment]
Thanks!

Unfortunately, this doesn't seem to work: 
Given the interrupt example, with the following loop function
`if(irmp_IsBusy()){
    Serial.println("Busy");
else{
    Serial.println("Not Busy");
}
delay(100);
`
This always prints busy.

**Comment by ArminJo** [comment]
Congratulation. 🥇 You tested the case I missed.
I updated the code with a version which also gives reliable results for interrupt mode 😀 .
