### ISSUE TITLE
proto_rf_medion missing from irmp_protocol_names

### ISSUE THREAD

**Issue by sej7278** [ukw100/IRMP#22]
`proto_rf_medion` is missing from `irmp_protocol_names` in 3.3.1 (its the only one, i went through them all as part of writing my app!); so `P=59` doesn't get converted to `P=RF_MEDION`, here's the one-liner fix - didn't bother with a PR:

```diff
simon@greivous:~/IRMP/src$ git diff
diff --git a/src/irmp.c.h b/src/irmp.c.h
index d20c214a..e7a46a99 100644
--- a/src/irmp.c.h
+++ b/src/irmp.c.h
@@ -835,7 +835,8 @@ irmp_protocol_names[IRMP_N_PROTOCOLS + 1] PROGMEM =
     proto_onkyo,
 
     proto_rf_gen24,
-    proto_rf_x10
+    proto_rf_x10,
+    proto_rf_medion
 };
 
 #endif
```

**Comment by ArminJo** [comment]
Thanks a lot!
I will wait a few days before the new bugfix Release.

**Comment by sej7278** [comment]
no problem, thanks for the lib!
