### ISSUE TITLE
Multiple definitions of Vector 3 when building with Servo_Attinycore - Tone-cpp.o?

### ISSUE THREAD

**Issue by smashteevee** [ukw100/IRMP#32]
### Arduino Platform
* [ ] Arduino ATmega328* board (UNO, Nano)
* [ ] Arduino ATmega2560 board (Mega)
* [ ] Arduino ATmega32U4 board (Leonardo)
* [ ] Arduino megaAVR board (NanoEvery)
* [ ] Arduino SAM board (Due)
* [ ] Arduino SAMD board (Zero, MKR*)
* [ x] ATtiny85 board (ATTinyCore by Spence Conde)
* [ ] Digispark board
* [ ] ATmega8 board
* [ ] ESP8266 board
* [ ] ESP32 board
* [ ] STM32 board with "STM32 Boards (selected from submenu)" core
* [ ] STM32 board with "STM32F1 Boards (STM32duino.com)" core
* [ ] Apollo3 board
* [ ] Teensy board
* [ ] Other - please specify

### IDE
* [ x] Arduino IDE
* [ ] Arduino Pro IDE
* [ ] Sloeber IDE
* [ ] PlatformIO IDE
* [ ] Other - please specify

### IR-Protocol
* [ ] Unknown
* [ ] Sony
* [ x] NEC
* [ ] Samsung
* [ ] RC5, RC6
* [ ] Kaseikyo
* [ ] Denon
* [ ] JVC
* [ ] Lego
* [ ] Matsushita
* [ ] Mitsubishi
* [ ] Panasonic
* [ ] Sanyo
* [ ] Sharp
* [ ] Telefunken
* [ ] Other - please specify

### Example to reproduce the issue
* [ ] AllProtocols
* [ ] Callback
* [ ] Interrupt
* [ ] OneProtocol
* [ ] ReceiveAndSend
* [ ] ReceiveAndSendDynamicPins
* [ ] RFProtocols
* [ ] SimpleReceiver
* [ ] SimpleSender
* [ x] MinimalReceiver

### Version
* [x ] Yes I use the [latest release](https://github.com/ukw100/IRMP/releases) and verified this!
* [ ] Other - please specify

### Current behavior
I am trying to utilize IRMP on an attiny85 using Attinycore (SpencerKonde core, no bootloader) and it's built-in Servo functionality.

When I add the following defines and headers to the top of the minimalReceiver sketch:

```
#define F_CPU 8000000
#define __AVR_ATtiny85__
#include <Servo_ATTinyCore.h>
```
my compile fails.

### Expected behavior
Expected that this would build successfully.

I am still reading up and learning about Timers and Interrupts, but I suspect this is related to Attinycore's Servo code to be compatible with Tone() and similar compatibility code built into IRMP.

### Error output

I get this compile eror:

`Tone.cpp.o (symbol from plugin): In function `tone(unsigned char, unsigned long, unsigned long)':
(.text+0x0): multiple definition of `__vector_3'
libraries/Servo_ATTinyCore/avr/Servo_ATTinyCore.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board ATtiny25/45/85 (No bootloader).
`
### Additional context

Is there a way to "disable" this redefinition of Tone() timer definition in IRMP?  I'd love to use IRMP along with Attinycore's Servo lib. Thanks for this great library and its many options (eg, Pin change interrupt option especially and ability to minimize protocol config)

**Comment by ArminJo** [comment]
Thanks for pointig this out 🥇 .
I commited the changes now, so use the current repo content or just remove the function irmp_tone() in irmpArduinoExt.cpp.h.
