### ISSUE TITLE
stm32 non interrupt mode

### ISSUE THREAD

**Issue by clear-sky** [ukw100/IRMP#4]
hi all
i have bluepill and tested many pins of this board all pins work in interrupt mode but could not find any pin that work in non interrupt mode 
is that possible to work in non interrupt mode? if possible which pins?

**Comment by ArminJo** [comment]
Hi,
please test the new version. It uses PA4 even on Arduino IDE. (their internal pin numbers are crazy...)

**Comment by clear-sky** [comment]
thanks problem solved
