### ISSUE TITLE
Benchmark Media protocol

### ISSUE THREAD

**Issue by lpaolini** [ukw100/IRMP#43]
I would like to add support for the [Benchmark remote control](https://benchmarkmedia.com/collections/parts/products/benchmark-remote-control-metal), which doesn't seem to be supported by any of the existing protocol, but I don't know exactly how to do that.

I've used a logic analyzer and measured the following timings:

- first bit pulse: 2.59ms
- first bit pause: 2.59ms
- pulse: 1.20ms
- short pause: 1.11ms
- long pause: 2.84ms
- data: 16bit
- stop bit: yes (pulse only)
- fsb/lsb: unknown
- interframe pause: 58ms

Do they resemble some known protocol?
If not, would it be possible for you to add support for it?
Perhaps you could create a branch for that, so that I can test it, and then submit a PR.

<img width="1746" alt="Screenshot 2021-02-03 at 00 25 23" src="https://user-images.githubusercontent.com/377807/106676027-7701ec00-65b6-11eb-9f33-9effdc578d04.png">
<img width="1746" alt="Screenshot 2021-02-03 at 00 25 33" src="https://user-images.githubusercontent.com/377807/106676034-78cbaf80-65b6-11eb-80a2-929f97172b46.png">
<img width="1746" alt="Screenshot 2021-02-03 at 00 25 44" src="https://user-images.githubusercontent.com/377807/106676038-79fcdc80-65b6-11eb-97d8-576b6f5514a4.png">
<img width="1746" alt="Screenshot 2021-02-03 at 00 25 55" src="https://user-images.githubusercontent.com/377807/106676040-7a957300-65b6-11eb-98c1-b501f3b44bbc.png">

**Comment by ArminJo** [comment]
Best is to use https://github.com/Arduino-IRremote/Arduino-IRremote use ir_Template.cpp or try to modify the ir_JVC.cpp timing. Then check if it is detected.
Best is if timing analysis can be done at the send diode, this removes the receiver pulse length distortions.

**Comment by lpaolini** [comment]
Ok thanks, I'll give it a try.
Do you think you'll add support for Teensy 4.x?

**Comment by ArminJo** [comment]
Sorry but there is no Teensy support possible, see: https://forum.pjrc.com/threads/65912-Enable-Continuous-Integration-with-arduino-cli-for-3-party-libraries 😞
But you can ask Paul, if he is willing to support 3. Party library developer better, than now.
