### ISSUE TITLE
bugs in irmpArduinoExt.cpp.h irmp_print_protocol_name

### ISSUE THREAD

**Issue by DamjanBabaVidin** [ukw100/IRMP#46]
## Bug Report
in  irmpArduinoExt.cpp.h - > irmp_print_protocol_name

if IRMP_PROTOCOL_NAMES == 1 
print both name and code example: SIRCS0x01
                                         has to be SIRCS
Bug is in lines:

#  endif
#endif
    aSerial->print(F("0x"));
    aSerial->print(aProtocolNumber, HEX);
}

To fix change to:

#  endif
#  else
    aSerial->print(F("0x"));
    aSerial->print(aProtocolNumber, HEX);
#endif
}

**Comment by ArminJo** [comment]
Thanks for reporting! 🥇
