### ISSUE TITLE
R repeat displaying even when pressing different buttons in a rapid manner

### ISSUE THREAD

**Issue by YUDHPK** [ukw100/IRMP#50]
If you have handling problems or questions, consider to open a discussion https://github.com/Arduino-IRremote/Arduino-IRremote/discussions instead of an issue.

### Board
* [x] Arduino ATmega328* board (UNO, Nano)

### IDE
* [x] Arduino IDE

### IR-Protocol
* [x] NEC

### Example to reproduce the issue
* [x] AllProtocols

### Version
* [x] Yes I use the [latest repo version](https://github.com/Arduino-IRremote/Arduino-IRremote/archive/master.zip) and verified this!

Please delete all unchecked lines above :-)

### Current behavior

VCC=4708mV
START /tmp/arduino_modified_sketch_450254/AllProtocols.ino from Jun  6 2021
Using library version 3.4.1
Ready to receive IR signals of protocols: SIRCS, NEC, SAMSUNG, MATSUSH, KASEIKYO, RECS80, RC5, DENON, RC6, SAMSG32, APPLE, RECS80EX, NUBERT, BANG OLU, GRUNDIG, NOKIA, SIEMENS, FDC, RCCAR, JVC, RC6A, NIKON, IR60, KATHREIN, NETBOX, NEC16, NEC42, THOMSON, BOSE, A1TVBOX, TELEFUNKEN, SPEAKER, LGAIR, SAMSG48, PENTAX, TECHNICS, MITSU_HEAVY, VINCENT, SAMSUNGAH, GREE, METZ, ONKYO, MELINERA, at pin 2
VCC=4708mV
P=NEC A=0x7F80 C=0x12
VCC=4708mV
P=NEC A=0x7F80 C=0x1A
P=NEC A=0x7F80 C=0x1E
P=NEC A=0x7F80 C=0x1E R
VCC=4708mV
VCC=4708mV
VCC=4708mV

the third line indicates a R that is a repeat command on serial monitor as well as on lcd display 16x2 whereas it shouldnt because i just pressed different buttons in a fast manner instead of pressing the same buttons repeatedly
### Expected behavior

when pressing different buttons in a fast manner it shouldnt print R anywhere (neither serial monitor nor lcd)
### Additional context

**checklist:**
- [x] I have **read** the README.md file thoroughly.
- [x] I have searched existing issues to see if there is anything I have missed.
- [x] I have browsed the examples for one, that matches my use case.
- [x] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here.
- [x] The title of the issue is helpful and relevant.
- [x] I checked, if at least one of the examples was working.

** We will start to close issues that do not follow these guidelines as it doesn't help the contributors who spend time trying to solve issues if the community ignores guidelines!**

**Comment by ArminJo** [comment]
With NEC, the repeat flag is only set if:
   - a repeat frame was received
   - the repeat frame was received no more than 40 msec after the original frame
   
I'm guessing that the remote control you are using polls with such a low sample rate that two very fast keystrokes count as one
long keystroke without release.
Logically, it sends one Repeat frame.
I have no other explanation.
You can also check with https://github.com/Arduino-IRremote/Arduino-IRremote/blob/master/examples/SimpleReceiver/SimpleReceiver.ino.
