### ISSUE TITLE
Arduino Due compatibility

### ISSUE THREAD

**Issue by gleanlux** [ukw100/IRMP#55]
Hello, 

I would like to inquire, is it possible to use this library on an Arduino DUE board?
The Arduino IDE compiler say, it's not compatible with "sam" boards.

Thank you very much for their help!

**Comment by ArminJo** [comment]
SAM is not listed here https://github.com/ukw100/IRMP#supported-arduino-architectures--cpus--boards

**Comment by gleanlux** [comment]
Yes, I understand, but expected to be included in the grant?

**Comment by ArminJo** [comment]
> but expected to be included in the grant?

I do not understand this sentence!

**Comment by gleanlux** [comment]
Sorry, my english isn't perfect.

I would like to same as, in other library.
I would like the library to support DUE.

**Comment by ArminJo** [comment]
DUE is a very poor supported platform 😞 .
But you are invited to try it.
