### ISSUE TITLE
stm32duino core ver 1.9 compile error

### ISSUE THREAD

**Issue by clear-sky** [ukw100/IRMP#6]
hi in stm32duino version 1.9 i get this compile error(https://github.com/stm32duino/Arduino_Core_STM32)

In file included from /home/conrad/Arduino/libraries/IRMP/src/irmp.c.h:30,
from /home/conrad/Arduino/libraries/IRMP/examples/AllProtocols/AllProtocols.ino:114:
/home/conrad/Arduino/libraries/IRMP/src/IRTimer.cpp.h: In function 'void initIRReceiveTimer()':
/home/conrad/Arduino/libraries/IRMP/src/IRTimer.cpp.h:174:43: error: no matching function for call to 'HardwareTimer::attachInterrupt(void (&)(HardwareTimer*))'
  174 | sSTM32Timer.attachInterrupt(irmp_timer_ISR); // this sets update interrupt enable

this error  does not exist in version 1.8 stm32duino

**Comment by ArminJo** [comment]
I opend an [issue](stm32duino/Arduino_Core_STM32/issues/1079) at stm32duino. 
You can fix the error by deleting line 37, 38, 39 and 41 in IRTimer.h.
