### ISSUE TITLE
esp8266 resets in non intrrupt mode

### ISSUE THREAD

**Issue by clear-sky** [ukw100/IRMP#63]
### Board
* [x] ESP8266 board

### IDE
* [x] Arduino IDE

### IR-Protocol
* [x] NEC

### Example to reproduce the issue
* [x] OneProtocol

### Version
* [x] Yes I use the [latest repo version](https://github.com/Arduino-IRremote/Arduino-IRremote/archive/master.zip) and verified this!
* [ ] Other - please specify

Please delete all unchecked lines above :-)

### Pin(s) used for IR-receive, if not default
gpio 12
### Current behavior
in itrrupt mode esp8266 work well but when i try it in non intrrupt mode mcu resets and i get this message in serial console

START OneProtocol.ino from Sep 12 2021
Using library version 3.4.1

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 3460, room 16 
tail 4
chksum 0xcc
load 0x3fff20b8, len 40, room 4 
tail 4
chksum 0xc9
csum 0xc9
v00042bd0
~ld

### Expected behavior
as far as i know main problem is in this function:
irmp_init();

### Additional context

i am trying to make a dotmatrix clock based on this project
https://github.com/tehniq3/ESP8266-LED-Matrix-Clock
but i have removed dht22 and replaced a vs838 ir sensor
ds3231 and ldr remains 
and this is vs838 wiring 
http://j5d2v7d7.stackpathcdn.com/wp-content/uploads/2016/11/VS838-application-circuit.gif

**checklist:**
- [y] I have **read** the README.md file thoroughly.
- [y] I have searched existing issues to see if there is anything I have missed.
- [y] I have browsed the examples for one, that matches my use case.
- [] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here.
- [] The title of the issue is helpful and relevant.
- [] I checked, if at least one of the examples was working.

** We will start to close issues that do not follow these guidelines as it doesn't help the contributors who spend time trying to solve issues if the community ignores guidelines!**

**Comment by clear-sky** [comment]
wow!!!
previous  version works
this is serial output:
START OneProtocol.ino from Sep 15 2021
Using library version 3.4.0
Ready to receive IR signals of protocols: NEC, APPLE, ONKYO, at pin 12
P=NEC0x2 A=0xFD01 C=0x83
P=NEC0x2 A=0xFD01 C=0x83 R
P=NEC0x2 A=0xFD01 C=0x93

**Comment by ArminJo** [comment]
Thanks a lot for hunting the bug.
It was the change from
`bool ICACHE_RAM_ATTR irmp_ISR(void)`
to 
`ICACHE_RAM_ATTR  bool irmp_ISR(void)`
that introduced the error

**Comment by clear-sky** [comment]
thanks for notice but problem has not been solved yet 
please see serial output:

START OneProtocol.ino from Sep 17 2021
Using library version 3.5.0

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 3460, room 16 
tail 4
chksum 0xcc
load 0x3fff20b8, len 40, room 4 
tail 4
chksum 0xc9
csum 0xc9
v00042bd0
~ld

**Comment by clear-sky** [comment]
in version 3.5.1 problem has been solved!
very very thanks for your notice!

**Comment by ArminJo** [comment]
Thanks for reporting !
